---
version: '3.7'
services:
  mysql:
    # *-----------------------------*
    # To connect to the DB:
    #   docker-compose exec mysql bash -c 'mysql -u root -p$MYSQL_ROOT_PASSWORD demo'
    # *-----------------------------*
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
     - MYSQL_DATABASE=openmrs
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
     - MYSQL_ROOT_HOST=172.%    # Allow docker contatiners to connect to mysql
    volumes:
     - ./mysql.cnf:/etc/mysql/conf.d/custom.cnf
     - ./dbdump:/docker-entrypoint-initdb.d

  openmrs:
    restart: "always"
    image: openmrs/openmrs-reference-application-distro:latest
    container_name: openmrs
    depends_on:
      - mysql
    links:
      - mysql:mysql
    ports:
      - "8080:8080"
    environment:
      DB_DATABASE: 'openmrs'
      DB_HOST: mysql
      DB_USERNAME: 'mysqluser'
      DB_PASSWORD: 'mysqlpw'
      DB_CREATE_TABLES: 'true'
