---
version: '3.7'
services:

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
#    container_name: elasticsearch
#    ports:
#      - 9200:9200
#    environment:
#      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    # volumes:
    #  - ${PWD}/scripts:/scripts

#  kibana:
#    image: docker.elastic.co/kibana/kibana:6.7.0
#    container_name: kibana
#    depends_on:
#      - elasticsearch
#    ports:
#     - 5601:5601
#    command:
#      - bash
#      - -c
#      - |
#        /usr/local/bin/kibana-docker &
#        echo "Waiting for Kibana to be ready (checking http://localhost:5601/api/status) ⏳"
#        while [ $$(curl -s http://streamserver.uksouth.cloudapp.azure.com:5601/api/status|grep --silent -e "\"status\":{\"overall\":{\"state\":\"green\"";echo $$?) -eq 1 ] ; do
#        sleep 5
#        done
#        echo "Pre-creating index pattern"
#        curl -XPOST 'http://streamserver.uksouth.cloudapp.azure.com:5601/api/saved_objects/index-pattern/mysql-debezium-dragon.openmrs.patient' \
#          -H 'kbn-xsrf: nevergonnagiveyouup' \
#          -H 'Content-Type: application/json' \
#          -d '{"attributes":{"title":"mysql-debezium-dragon.openmrs.patient","timeFieldName":"CREATE_TS"}}'

#        echo "Setting the index pattern as default"
#        curl -XPOST 'http://streamserver.uksouth.cloudapp.azure.com:5601/api/kibana/settings' \
#          -H 'kbn-xsrf: nevergonnagiveyouup' \
#          -H 'content-type: application/json' \
#          -d '{"changes":{"defaultIndex":"mysql-debezium-dragon.openmrs.patient"}}'

#        echo "Opting out of telemetry"
#        curl -XPOST 'http://streamserver.uksouth.cloudapp.azure.com:5601/api/telemetry/v1/optIn' \
#          -H 'kbn-xsrf: nevergonnagiveyouup' \
#          -H 'content-type: application/json' \
#          -d '{"enabled":false}'

#        sleep infinity

  neo4j:
    image: neo4j:3.4-enterprise
    container_name: neo4j
    ports:
    - "7474:7474"
    - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/connect
      NEO4J_dbms_memory_heap_max__size: 8G
      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
